services:
  arduino_bridge:
    build:
      context: ./ros_arduino_bridge
      dockerfile: Dockerfile
    environment:
      - VESSEL_ID=$VESSEL_ID
      - RMW_IMPLEMENTATION=$RMW_IMPLEMENTATION
    privileged: true
    volumes:
      - /dev:/dev
    container_name: ros_arduino_bridge
    network_mode: "host"     
  
  emlid_bridge:
    build:
      context: ./ros_emlid_bridge
      dockerfile: Dockerfile
    environment:
      - VESSEL_ID=$VESSEL_ID
      - RMW_IMPLEMENTATION=$RMW_IMPLEMENTATION
    container_name: ros_emlid_bridge
    network_mode: "host"
